### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pierry**

### CODE REVIEW

**Comment by JakeWharton** [comment]
The `install.sh` script should work on Mac. It's what I've always used. Is it not working for you?

**Comment by Pierry** [comment]
I am using El Capitan, installed 2 days ago, and it is not work for me. Sorry =/

**Comment by benjohnde** [comment]
Works for me on El Capitan :+1:.

**Comment by JakeWharton** [comment]
We added `install.bat` for Windows. Closing since `install.sh` should work for Macs and linux.

**Pull request closed without merging**
