### PR TITLE
Add support for settings repository

### LINKED ISSUE #74: Consider converting to a settings repository
https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html#share-more-settings-through-read-only-repo

### LINKED ISSUE #87: Support settings repository
While @JakeWharton brought up converting this entire thing to a settings repository (https://github.com/square/java-code-styles/issues/74), this is a request to support personal settings-repositories.

### PR DESCRIPTION
**Pull request by kwonye**
Resolves #87 

This adds support for users who have their own settings repository they read from

### CODE REVIEW

**Comment by pforhan** [comment]
LGTM

**Review by pforhan — APPROVED** [review]

**Comment by kwonye** [comment]
Thanks @pforhan! I'm unable to merge so please merge whenever you see fit, thanks 👍

**Review by syadu1988 — APPROVED** [review]

**Review by swankjesse — APPROVED** [review]

**Comment by pforhan** [comment]
can someone go ahead and merge?

**Comment by syadu1988** [comment]
Should we merge this @pforhan @kwonye ? I don't have merge access.

**Comment by pforhan** [comment]
@vRallev @JakeWharton @swankjesse are the last three mergers I see in history -- anyone want to take a look?

**Comment by vRallev** [comment]
@swankjesse approved, will merge.

**Pull request merged**
