### PR TITLE
New Kotlin formatting options

### PR DESCRIPTION
**Pull request by zach-klippenstein**
- Applied the default settings from the Kotlin style guide using the new plugin with more formatting support.
- Tweaked the settings a bit to match our existing style better.

image

### CODE REVIEW

**Comment by JakeWharton** [comment]
Update both styles? Or maybe just delete the Android-specific one and unify them...

**Comment by zach-klippenstein** [comment]
I'll apply the kotlin stuff to both files for now – merging them is going to have a larger impact so I'll leave that for another PR.

**Comment by JakeWharton** [comment]
👍 

I already have #45 filed for merging the two. Just hoping for a volunteer.

**Comment by zach-klippenstein** [comment]
I've copied the kotlin changes into the non-Android file.

**Pull request merged**
