### PR TITLE
Track the Kotlin code styles we've adopted in Misk

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by swankjesse** [comment]
screen shot 2018-02-24 at 5 12 48 pm

**Comment by swankjesse** [comment]
screen shot 2018-02-24 at 5 48 07 pm

**Comment by VasileUngureanu** [comment]
Hi,

With every new version of code styles you apply them to all existing code (that is formatted with previous version of code styles) or you apply them only to new code/project? ))

**Comment by swankjesse** [comment]
I’ve been doing the latter. But we don’t have _that_ much non-Android Kotlin code at the moment.

**Comment by swankjesse** [comment]
https://github.com/square/misk/pull/119

**Pull request merged**
